### ISSUE TITLE
Problema con link a Linkedin

### ISSUE THREAD

**Issue by tsukitaro** [C4rL0Xt/C4rL0Xt#1]
Hola como se encuentra

Queria comentarle que tienes un problema con el link de linkedin, no esta trabajando correctamente,
Esta en el README.md
```html
## 📫 Let's Connect

<div align="center">
  <a href="www.linkedin.com/in/carlos-daniel-espinoza-ramirez-7827a62aa"><img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" /></a>
```
Esto se debe a que en el anchor tag
```html
<a href="www.linkedin.com/in/carlos-daniel-espinoza-ramirez-7827a62aa">
``` 
Estas escribiendo el link sin el protocolo, entonces github no lo reconoce como un link al sitio Linkedin si no como un recurso el cual no encuentra 

![image](https://github.com/user-attachments/assets/32d3ab91-8798-43af-9f63-13bfca278344)

Esto lo arreglas escribiendo el protocolo **https://** al inicio de www
```html
<a href="https://www.linkedin.com/in/carlos-daniel-espinoza-ramirez-7827a62aa">
``` 
No sabia si te molestaria un PR a esto, entonces te lo comento por aqui, espero no te moleste
te encontre por el proyecto que subiste a [Roadmap.sh](https://www.roadmap.sh/projects) de java

**Comment by C4rL0Xt** [comment]
graciasss bro
